spring:
  application:
    name: Backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.web: DEBUG
    com.LinktoSync: DEBUG

app:
  security:
    username: ${APP_USERNAME}
    password: ${APP_PASSWORD}
